#!/bin/bash
sudo add-apt-repository -y ppa:martin-frost/thoughtbot-rcm
sudo add-apt-repository -y ppa:cpick/hub
sudo apt-get update
sudo apt-get install -y hub
sudo apt-get install -y rcm
sudo apt-get install -y silversearcher-ag
su -c "cd /home/vagrant/.dotfiles && ./install.rb" vagrant
