tap "thoughtbot/formulae"
tap "sharplet/formulae"
brew "ag"
brew "chisel"
brew "icdiff"
brew "git"
brew "gnupg"
brew "hub"
brew "jq"
brew "kylef/formulae/swiftenv"
brew "rcm"
# brew "todogrep"
brew "tmux"
brew "vim"
