# vim: ft=ruby
tap "sharplet/formulae"
tap "thoughtbot/formulae"
brew "ag"
brew "chisel"
brew "icdiff"
brew "git"
brew "gnupg"
brew "hub"
brew "jq"
brew "kylef/formulae/swiftenv"
brew "rcm"
brew "swift-spec"
# brew "todogrep"
brew "tmux"
brew "vim"
