#!/bin/bash

# print the last touched file in this directory
function lf()
{
  ls -t $@ | grep -v '^total' | head -1
}

# edit the last touched file with EDITOR
function elf()
{
  [ "x$EDITOR" != "x" ] && $EDITOR "$(lf)"
}

# open in Xcode
function xc()
{
  local xcpath=$(dirname $(dirname $(xcode-select -p)))
  open -a "$xcpath" $@
}

# start a new scratch project
function scratch()
{
  readonly scratch_dir="${HOME}/src/scratch/$1"
  git init "${scratch_dir}"
  cd "${scratch_dir}"
}
