#!/bin/sh

set -o pipefail

# present a project selector and change to the selected directory
go() {
  base=${1:-$PROJ_ROOT}
  if [ -z "$base" ]; then
    echo >&2 "error: PROJ_ROOT must be set or a base directory passed as the first argument"
    return 1
  fi

  dir=$(
    cd "$base" &&
      ls-projects --exclude '^(?!src)' 2>/dev/null \
        | xargs ls -dt \
        | fzf --reverse -d/ --with-nth=2..
  )

  # after selecting a project, expand it back out to its full path and jump to it
  if [ -n "$dir" ]; then
    dest="$base/$dir"
    touch "$dest" && cd "$dest" || return
  fi
}

command_exists() {
  command -v "$@" >/dev/null
}

exit_status_colors() {
  # shellcheck disable=SC2181
  exit_status=$?

  cyan=\\e\[36\;1m
  red=\\e\[31\;1m
  reset=\\e\[0m

  if [ $exit_status != 0 ]; then
    echo "$red$*$reset"
  else
    echo "$cyan$*$reset"
  fi
}
