#!/usr/bin/ruby

def commit_msg_empty?(msg)
  msg.lines.grep(/^(?!#).*\S.*^/).empty?
end

commit_msg_file, commit_type, ref = *ARGV

case [commit_type, ref]
when ["commit", "HEAD"] # amending
when ["merge", nil]
  # do nothing
else
  commit_msg = File.read(commit_msg_file)
  current_branch = %x(git branch | sed -n 's/^* //p').chomp

  if commit_msg_empty?(commit_msg) && current_branch =~ %r{\A([\w-]+)/([\w-]+)/([\w-]+)\z}
    jira_no = $2.upcase
    jira_msg = commit_msg.sub(/\A/, "[#{jira_no}]: ")

    File.write(commit_msg_file, jira_msg)
  end
end
