#!/usr/bin/env bash

plistbuddy=/usr/libexec/PlistBuddy

list_xcodes() {
  find /Applications/Xcode*.app -name Info.plist -maxdepth 2 \
    -exec echo -n "{} " \; \
    -exec $plistbuddy -c 'Print :CFBundleVersion' {} \; \
    | sort -n -k 2 \
    | cut -d " " -f 1 \
    | grep -E -o '^.+\.app'
}

list_xcodes | nl -b a -n rn -s ".	"

declare -i selection

echo -n "Choose Xcode: "
read -r selection

if [[ $selection == 0 ]]; then
  echo >&2 "Invalid selection"
  exit 1
fi

xcode_path="$(list_xcodes | sed "${selection}q;d")"

echo "Switching to ${xcode_path}..."
sudo xcode-select --switch "${xcode_path}"
