#!/usr/bin/env bash

set -eo pipefail

current_branch=$(git branch | sed -E -n 's/^\* (.+)$/\1/p')

if [ "$current_branch" != "master" ]; then
  echo "You must be on master to close a pull request." >&2
  exit 1
fi

branch="$1"

if [ -z "$branch" ]; then
  echo "specify a branch to close" >&2
  exit 1
fi

git merge --ff-only "$branch" \
  && git push --atomic origin master ":$branch" \
  && git branch -d "$branch"
