#!/usr/bin/env bash

set -eo pipefail

current_branch=$(git branch | sed -E -n 's/^\* (.+)$/\1/p')
force=false

while getopts f opt; do
  case $opt in
    f)
      force=true
      ;;
    *)
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

if [ $# -lt 1 ]; then
  echo "specify a branch to close" >&2
  exit 1
fi

branch="$1"

if [ "$force" != true ] && [ "$current_branch" != "master" ]; then
  echo "You must be on master to close a pull request." >&2
  echo "Either check out 'master' or specify '-f' to continue." >&2
  exit 1
fi

git merge --ff-only "$branch" \
  && git push --atomic origin master ":$branch" \
  && git branch -d "$branch"
