#!/usr/bin/env bash

set -eo pipefail

current_branch=$(git branch | sed -E -n 's/^\* (.+)$/\1/p')
merge_option="--ff-only"

for opt; do
  case $opt in
    -f|--force)
      force=true
      ;;
    --no-ff)
      merge_option="--no-ff"
      ;;
    *)
      break
      ;;
  esac

  shift
done

if [ $# -lt 1 ]; then
  echo "specify a branch to close" >&2
  exit 1
fi

branch="$1"

if [ "$force" != true ] && [ "$current_branch" != "master" ]; then
  echo "You must be on master to close a pull request." >&2
  echo "Either check out 'master' or specify '-f' to continue." >&2
  exit 1
fi

git merge "$merge_option" "$branch" \
  && git push origin "$current_branch" \
  && git push origin ":$branch" \
  && git branch -d "$branch"
