#!/bin/bash
#
# Find TODO and FIXME directives in the current git repository or directory.
# Exits with a non-zero status if any results are found.
#
# Usage:
#   todogrep [options]
#
# Options:
#   -i <pattern>    Include files matching <pattern> (multiple patterns can be specified)
#   -e <pattern>    Exclude files matching <pattern> (multiple patterns can be specified)
#   -f <format>     Format output: use 'warn' to format like a compiler warning (also preventing a non-zero exit status).
#                   Default value is 'none'.
#   -m <mode>       Search mode:
#                    - 'git'       Use `git ls-files` to only search tracked files.
#                    - 'find'      Recursively search the current directory for files.
#                    - 'default'   This is the default value, which tries to use 'git' when inside a git repository, and falls back to 'find'.

## Finding files

find_files() {
  search_mode=$1

  if [ "${search_mode}" = "default" ]; then
    if in_git_dir
    then search_mode="git"
    else search_mode="find"
    fi
  fi

  if [ "${search_mode}" = "git" ]; then
    git ls-files
  elif [ "${search_mode}" = "find" ]; then
    find . -type f | sed 's/^.\///'
  else
    echo "todogrep: unsupported file search mode '${search_mode}'" >&2
    exit 1
  fi
}

in_git_dir() {
  [ -d .git ] || git rev-parse --git-dir > /dev/null 2>&1
}

## Filtering files

accept_paths() {
  ([ ${#*} -gt 0 ] && egrep ${*} || exec cat)
}

reject_paths() {
  ([ ${#*} -gt 0 ] && egrep -v ${*} || exec cat)
}

## Formatting output

format_results() {
  mode=$1; shift

  case ${mode} in
    warn)
      format_warn ${*}
      ;;
    none)
      cat
      ;;
    *)
      echo "todogrep: unsupported format mode '${mode}'" >&2
      exit 1
      ;;
  esac
}

format_warn() {
  anchor=$1

  sed -lnE "s/(($anchor).*)$/warning: \\1/p"
}

## Helpers

nullify() {
  tr "\n" "\0"
}

fail_on_output() {
  ruby -pe 'BEGIN{$ret=0}; $ret=1; END{exit $ret}'
}

## Main

declare -a includes
declare -a excludes
declare format_mode="none"
declare search_mode="default"
declare keywords="FIXME:|TODO:"

while getopts e:i:f:m: opt; do
  case $opt in
    i)
      includes+=("-e")
      includes+=("$OPTARG")
      ;;
    e)
      excludes+=("-e")
      excludes+=("$OPTARG")
      ;;
    f)
      format_mode="$OPTARG"
      ;;
    m)
      search_mode="$OPTARG"
      ;;
  esac
done

shift $((OPTIND - 1))

set -o pipefail

find_files ${search_mode} \
  | accept_paths ${includes[*]} \
  | reject_paths ${excludes[*]} \
  | nullify \
  | xargs -0 egrep --directories=skip --with-filename --line-number --only-matching "[[:space:]]?($keywords).*$" \
  | format_results ${format_mode} ${keywords} \
  | fail_on_output

code=$?

if [ ${format_mode} = "warn" ]; then
  exit
else
  exit ${code}
fi
