#!/bin/sh
#
# Open the specified path using the current Xcode.

set -e

scriptname() {
  basename "$0"
}

xcpath=$(xcode-select -p | grep -E -o '^.+\.app')

if [ $# -lt 1 ]; then
  echo >&2 "$(scriptname): must specify a path to open"
  exit 1
fi

exec open -a "$xcpath" "${@}"
